# Site settings
title: Jules Belveze
description: "Thoughts, notes, and links."

# Use GitHub Pages-supported theme
remote_theme: mmistakes/minimal-mistakes

# Optional: simple RSS/Atom feed (works on GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# When you know your domain, uncomment and set these
# url: https://yourusername.github.io
# baseurl: "" # keep empty for user/organization site

# Theme options
minimal_mistakes_skin: "dirt" # e.g., default, air, aqua, contrast, dark, dirt, neon, mint, midnight, sunrise

# Build and content structure
permalink: /:categories/:title/
timezone: UTC

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false

exclude:
  - vendor
  - node_modules
  - README.md
  - Gemfile.lock
  - .gitignore
  - .DS_Store

# Minima options
show_excerpts: true

# Home page shows latest posts via manual loop in index.md

social:
  github: "https://github.com/JulesBelveze"
  x: "JulesBelveze"
  linkedin: "https://www.linkedin.com/in/jules-belveze/"

# Favicon image path (relative or absolute). Default uses an SVG placeholder.
favicon: /assets/images/logo.png

# Optional logo (used next to the site title in the header and on the home page icon).
# Replace with your PNG/SVG path to your avatar/icon.
logo: /assets/images/logo.png
